FORMAT: 1A
HOST: seed-it.eu:4000

# API Seeds
An API for sensor data exchange

# Groups Sensor

## Sensor [/sensor]

### Insert new sensor data [POST]

+ Request
    + Headers

            Host:seed-it.eu:4000
            User-Agent:curl/7.67.0
            Accept:*/*
            Content-Type:application/json
            Content-Length:85

    + Body

            {"datetime":"2019-01-01T01:01:00","temperature":22.1,"humidity":22.1,"pressure":22.1}

+ Response 201
    + Headers

            Date:Wed, 20 Nov 2019 18:20:50 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            {"message":"Item created"}

### Get sensor data list [GET]

+ Request
    + Headers

            Host:seed-it.eu:4000
            User-Agent:curl/7.67.0
            Accept:*/*
            Content-Type:application/json

    + Body



+ Response 200
    + Headers

            Date:Wed, 20 Nov 2019 18:52:05 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            [ {

              "datetime" : "2019-11-14T10:11:59.378308",

              "temperature" : 21.25,

              "humidity" : 46.8,

              "pressure" : 1013.111

            } ]
