FORMAT: 1A
HOST: localhost:4000

# API Seeds
An API for interractions between a mariadb database and the PHP webserver

# Group Seeds

## Seeds List [/seeds]

### Get seeds [GET]
+ Request
    + Headers

            Host:localhost:4000
            User-Agent:curl/7.66.0
            Accept:*/*

    + Body



+ Response 200
    + Headers

            Date:Fri, 25 Oct 2019 09:11:35 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            [ {
              "id" : 0,
              "name" : "Potiron",
              "description" : "Une des cinq espèces de courges les plus couramment cultivées",
              "tips" : null
            }, {
              "id" : 1,
              "name" : "Tomate",
              "description" : "Une espèce de plantes herbacées",
              "tips" : null
            } ]

## Seed [/seed/{seed_id}]

+ Parameters

    + seed_id (required, int) - The seed id

### Get Seed [GET]
Get a single seed


+ Request
    + Headers

            Host:localhost:4000
            User-Agent:curl/7.66.0
            Accept:*/*

    + Body


+ Response 200
    + Headers

            Date:Fri, 25 Oct 2019 09:17:27 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            {
              "id" : 1,
              "name" : "Tomate",
              "description" : "Une espèce de plantes herbacées",
              "tips" : null
            }


+ Response 404
    + Headers

            Date:Fri, 25 Oct 2019 09:17:35 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            {"message":"Seed not found"}


### Insert new seed [POST]

+ Request
    + Headers

            Host:localhost:4000
            User-Agent:curl/7.66.0
            Accept:*/*
            Content-Type:application/json
            Content-Length:39

    + Body

            {"name":"ananas", "description":"test"}

+ Response 201
    + Headers

            Date:Fri, 25 Oct 2019 14:21:06 GMT
            Content-Encoding:gzip
            Content-Type:application/json
            Transfer-Encoding:chunked
            Server:Jetty(9.4.z-SNAPSHOT)

    + Body

            {"message":"Inserted seed"}
